spring:
  config:
    activate:
      on-profile: local

  datasource:
    hikari:
      jdbc-url: jdbc:mysql://${LOCAL_DATABASE_URL}/blog
      username: ${LOCAL_DATABASE_USERNAME}
      password: ${LOCAL_DATABASE_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
      pool-name: MyChatConnectionPool
      minimum-idle: 10 # 최소 커넥션
      maximum-pool-size: 50 # 최대 커넥션
      idle-timeout: 60000
      connection-timeout: 30000

  sql:
    init:
      mode: always
    log:
      format: true
    statements: true

  logging:
    level:
      org:
        springframework:
          jdbc: DEBUG


---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url:
    driver-class-name: com.mysql.cj.jdbc.Driver


  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
    log:
      format: true
    statements: true

logging:
  level:
    org:
      springframework:
        jdbc: DEBUG

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    hikari:
      jdbc-url: jdbc:mysql://${PROD_DATABASE_URL}/blog
      username: ${PROD_DATABASE_USERNAME}
      password: ${PROD_DATABASE_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
      pool-name: MyChatConnectionPool
      minimum-idle: 10 # 최소 커넥션
      maximum-pool-size: 50 # 최대 커넥션
      idle-timeout: 60000
      connection-timeout: 30000
