services:
  mysql:
    image: mysql:8.0.40
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: qwer1234
      MYSQL_DATABASE: codestream
      MYSQL_USER: jungmini
      MYSQL_PASSWORD: qwer1234
    ports:
      - "13306:3306"
    volumes:
      - ./mysql/volume:/var/lib/mysql
    networks:
      - blog

  redis:
    image: redis:7.4.1
    restart: unless-stopped
    command: redis-server --requirepass jungmini
    ports:
      - "16379:6379"
    volumes:
      - ./redis/volume:/data
    networks:
      - blog

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/config:/etc/prometheus
      - ./prometheus/volume:/prometheus
    ports:
      - "19090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped
    networks:
      - blog

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "13000:3000"
    volumes:
      - ./grafana/volume:/var/lib/grafana
    networks:
      - blog

networks:
  blog:
    driver: bridge