# 댓글 생성
POST http://{{host}}/v1/comments
Content-Type: application/json

{
  "postId": 2,
  "parentId": 1,
  "content": "댓글 내용"
}
###

# 댓글 수정
PUT http://{{host}}/v1/comments/1
Content-Type: application/json

{
  "content": "수정"
}