# 팔로우 생성
POST http://{{host}}/v1/follows/1

###

# 팔로우 삭제
DELETE http://{{host}}/v1/follows/6

###

# 유저 아이디가 팔로잉 하고 있는 사람 조회
GET http://{{host}}/v1/followees/1
###

# 유저아이디를 팔로우 하고 있는 사람 조회
GET http://{{host}}/v1/followers/1
