# 회원 가입
POST http://{{host}}/v1/users/register
Content-Type: application/json

{
  "email": "jungmini0602@gmail.com",
  "nickname": "jungmini",
  "password": "qwer1234"
}
###

# 내 정보 조회
GET http://{{host}}/v1/users/me
###

# 회원 정보 수정
PUT http://{{host}}/v1/users/update
Content-Type: application/json

{
  "nickname": "수정닉네임"
}

###

# 회원 정보 삭제
DELETE http://{{host}}/v1/users/remove